eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      #defaultZone: http://eureka.pre-youle.sioeye.com/eureka/
      defaultZone: http://localhost:7000/eureka/
  server:
    enable-self-preservation: false
    # 服务器间隔时间删除无效实例（默认60000）
    eviction-interval-timer-in-ms: 10000
logging:
  file: \sioeye\disney\logs\springcloud\eureka\eureka.log
  level:
    org:
      springframework:
        boot: info
server:
  port: 7000
spring:
  application:
    name: youle-common-eureka